### ISSUE TITLE
vite 搭建未支持 【按需引用】

### ISSUE THREAD

**Issue by tairenzhen** [view-design/ViewUIPlus#102]
import Components from 'unplugin-vue-components/vite'
import {ElementPlusResolver} from 'unplugin-vue-components/resolvers'

Components({
            // `customComponentsResolvers` has renamed to `resolver`
            resolvers: [
                ElementPlusResolver(),
            ],
        }),

![image](https://user-images.githubusercontent.com/22595272/174565937-d6194e0c-fea1-47ce-8af3-2e8c03526f5d.png)

**Comment by likuner** [comment]
我们已经向vue官方提交pr，待合并后，引入ViewUIPlusResolver才能支持在vite环境下的按需加载。

**Comment by tairenzhen** [comment]
你好，邮件我已收到，我会尽快给你回复，谢谢！                                                    ——郭泰

**Comment by superlbr** [comment]
considering lots of iview user, view-ui series just need a proper migrate guide.

**Comment by tairenzhen** [comment]
你好，邮件我已收到，我会尽快给你回复，谢谢！                                                    ——郭泰

**Comment by lin09** [comment]
- https://github.com/unplugin/unplugin-vue-components/pull/404#issuecomment-1432790490
😂unplugin-vue-components不再接受新的解析器

**Comment by tairenzhen** [comment]
你好，邮件我已收到，我会尽快给你回复，谢谢！                                                    ——郭泰
