### ISSUE TITLE
组合式api中调用组件实例方法报错

### ISSUE THREAD

**Issue by ls956766224** [view-design/ViewUIPlus#107]
在setup语法糖中调用 Message.xx()，无论是全局绑定还是在单文件中引入或者使用provide/inject；都报相同的错误，如下：

![1656132242453](https://user-images.githubusercontent.com/108166358/175758360-a95fc5f8-7e98-4daf-ac92-1bd041d1d857.png)

**Comment by icarusion** [comment]
按要求提交 issue

**Comment by iamziyue** [comment]
出现同样的问题，竟然需要这样用：
```javascript
ctx.$nextTick(() => {
  ctx.$Message.success('123')
})
```
奇怪了，弹出提示的方法是在onMounted里面调用的，view-ui-plus的源码中`const s = i.refs.notification`竟然没有拿到实例。
