### ISSUE TITLE
[Bug Report]Login 登录

### ISSUE THREAD

**Issue by shihongfu** [view-design/ViewUIPlus#138]
### Environment
win10，谷歌浏览器，vue3

### Reproduction link
[https://run.iviewui.com/9TwlCYoC](https://run.iviewui.com/9TwlCYoC)

### Steps to reproduce
/**
   下面是按照官网写法，浏览器控制台不报错，但是验证码自定义验证失效
**/
<template>
	<div class="container">
		<Login @on-submit="handleSubmit">
			<Mobile name="mobile" value="18165275209"/>
			<Captcha name="mobileCaptcha" :field="['mobile']" :rules="mobileCaptcha" @on-get-captcha="handleGetCaptcha" />
			<div class="demo-auto-login">
				<a class="a1">注册登记</a>
			</div>
			<Submit />
		</Login>
	</div>
</template>
<script>
import { reactive, toRefs,ref, onBeforeMount, onMounted ,getCurrentInstance} from 'vue';

export default {
  name: 'login',
  setup(props,context) {
		const data = reactive({
			LoginCode:'6753',  //刷新后的验证码
			mobileCaptcha: [{ validator: validatePassCheck, trigger: 'change' }]
		});
		const validatePassCheck = (rule, value, callback) => {
		    if (value !== data.LoginCode) {
		        callback(new Error('短信验证码不匹配，请重新输入！'));
		    } else {
		        callback();
		    }
		};
		const handleGetCaptcha = () => {
			proxy.$Message.info({
			    content: '验证码发送成功'
			});
		};
		const handleSubmit = (valid, { mobile, mobileCaptcha }) => {
			if (valid) {
			   console.log({ mobile, mobileCaptcha })
			}
		};
		return {
			...toRefs(data),
			handleSubmit,
			handleGetCaptcha,
			validatePassCheck
		};
	}
};
</script>

/**
   下面是按照我自己修改后的写法，浏览器控制台报错，但是验证码自定义验证有效

  报错内容：
        [Vue warn]: Invalid prop: type check failed for prop "rules". Expected Object | Array, got Function  
  at <Captcha name="mobileCaptcha" field= Array(1) rules=fn<validatePassCheck>  ... > 
  at <IForm ref="form" model= Object onSubmit=fn > 
  at <Login onOnSubmit=fn<handleSubmit> > 
  at <Login onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App>
**/

<template>
	<div class="container">
		<Login @on-submit="handleSubmit">
			<Mobile name="mobile" value="18165275209"/>
			<Captcha name="mobileCaptcha" :field="['mobile']" :rules="validatePassCheck" @on-get-captcha="handleGetCaptcha" />
			<div class="demo-auto-login">
				<a class="a1">注册登记</a>
			</div>
			<Submit />
		</Login>
	</div>
</template>
<script>
import { reactive, toRefs,ref, onBeforeMount, onMounted ,getCurrentInstance} from 'vue';

export default {
  name: 'login',
  setup(props,context) {
		const data = reactive({
			LoginCode:'6753',  //刷新后的验证码
			mobileCaptcha: [{ validator: validatePassCheck, trigger: 'change' }]
		});
		const validatePassCheck = (rule, value, callback) => {
		    if (value !== data.LoginCode) {
		        callback(new Error('短信验证码不匹配，请重新输入！'));
		    } else {
		        callback();
		    }
		};
		const handleGetCaptcha = () => {
			proxy.$Message.info({
			    content: '验证码发送成功'
			});
		};
		const handleSubmit = (valid, { mobile, mobileCaptcha }) => {
			if (valid) {
			   console.log({ mobile, mobileCaptcha })
			}
		};
		return {
			...toRefs(data),
			handleSubmit,
			handleGetCaptcha,
			validatePassCheck
		};
	}
};
</script>

### What is expected?
浏览器控制台报错，并且功能正常使用

### What is actually happening?
浏览器控制台不报错的官方版本，功能失效

---
是否有bug，请尽快回复

**Comment by likuner** [comment]
报错很明显是你传的值不对 改成这个 rules="mobileCaptcha"
