### ISSUE TITLE
Could you please start using English?

### ISSUE THREAD

**Issue by luckylooke** [view-design/ViewUIPlus#157]
What problem does this feature solve?
Project is unusable worldwide as most of parts are not in English

What does the proposed API look like?
Translate everything on page to English, push users to write issues in English

Examples:
<img width="1363" alt="Screenshot 2022-08-14 at 09 44 13" src="https://user-images.githubusercontent.com/3660030/184527581-ffa8ef2c-be51-4330-88c8-36fe06277565.png">
<img width="2154" alt="Screenshot 2022-08-14 at 09 39 53" src="https://user-images.githubusercontent.com/3660030/184527583-2ba0fa59-89ef-47b2-b5ed-15cf74e9434c.png">

**Comment by icarusion** [comment]
Our products currently only support English in ViewUIPlus, other products do not currently support English
