### ISSUE TITLE
[Bug Report]非template/render模式Tree右键菜单不能显示Dropdown-Item

### ISSUE THREAD

**Issue by lastonesky** [view-design/ViewUIPlus#198]
### Environment
Windows 11/Edge  107.0.1418.26/Vue 3

### Reproduction link
[https://jsrun.net/NesKp/edit](https://jsrun.net/NesKp/edit)

### Steps to reproduce
右键点击Tree上的任何内容即可重现

### What is expected?
能显示Dropdown-Item里的内容

### What is actually happening?
只显示了一个方块，任何菜单项都没显示

---
template/render模式没有问题

**Comment by 95616** [comment]
同问，非template/render模式 table,tabs 也都无法加载右键菜单 solt ；楼主找到原因了吗

**Comment by lastonesky** [comment]
没找到原因，但是可以通过其他方式绕过这个问题
