### ISSUE TITLE
[Feature Request]Select组件 在开启可搜索并选择了选项后，能在不清空选项的情况下显示所有选项

### ISSUE THREAD

**Issue by JokanJan** [view-design/ViewUIPlus#227]
### What problem does this feature solve?
现在只能先清空选项，才能选择其它选项。旧版本的iview不需要这样操作

### What does the proposed API look like?
开启可搜索后不清空选项，选项列表也能显示其他选项

**Comment by zhangbing3** [comment]
@icarusion vue3版本的代码跟vue2版本的代码这个显示逻辑变了，因为vue3版本少了SelectInstance.filterQueryChange这个状态的判断，才导致选中了之后，再打开下拉框，下拉框会直接过滤，目前改的选中之后是不会过滤了，但是改变query值它也不过滤了，建议在1.3.1版本的逻辑上面增加 !SelectInstance.filterQueryChange 判断。
