### ISSUE TITLE
[Select][Bug]使用Select时，异步请求Options数据和设置默认值，value为数字时，默认不能选中

### ISSUE THREAD

**Issue by DebugIsFalse** [view-design/ViewUIPlus#299]
### 复现Demo地址
https://run.iviewui.com/GRUQ1GUj

### 导致此bug的问题是处理Option默认选中值出现问题
1. 如果默认值为0会出问题
2. 默认值是数字导致异常
```
文件路径：src/components/select/option.vue 
147行:  modelValue && modelValue.toString().length && select.lazyUpdateValue(true);
```

**Comment by JHanL** [comment]
我遇到了同样的问题，之前也提过，但是官方没给出解决方案  https://github.com/view-design/ViewUIPlus/issues/296

**Comment by JHanL** [comment]
我们下个项目还是准备用ant-desgin的组件库，view-puls-ui开发起来问题太多了，效率低下，官方还不怎么维护。

**Comment by deniel-feng** [comment]
可以试下这个，当异步选项变化的强制给select组件的values赋值，我测试的是可行的
this.$refs.Select.values = [{value: 1296, label: 'test_02', tag: null}];

**Comment by Sunrisies** [comment]
直接把数字类型的转出字符串类型就可以了

**Comment by EEEVO** [comment]
试过了吗？？？还是没有解决啊

https://run.iviewui.com/3hdUS9Go

简化了代码了
