### ISSUE TITLE
[Bug Report]Uncaught TypeError: Cannot read properties of null (reading 'isCE')

### ISSUE THREAD

**Issue by chougaigai** [view-design/ViewUIPlus#346]
### Environment
chrome/vue3.2.45

### Reproduction link
[https://www.baidu.com/](https://www.baidu.com/)

### Steps to reproduce
引入view-ui-plus之后。使用Form表单。报错Uncaught TypeError: Cannot read properties of null (reading 'isCE')。
之前都是可以的。今天突然报错。新建新的项目引入view-ui-plus后用Form也是报错。
<img width="691" alt="image" src="https://github.com/view-design/ViewUIPlus/assets/32348909/c9f93ba0-84a7-4f34-83f1-b44f0065f3e5">

### What is expected?
解决正常运行

### What is actually happening?
报错无法运行

**Comment by GreenRun0912** [comment]
我也出现这个问题了，vue版本升级到3.4.5之后就报这个错，回退到3.4.4就没事，3.4.5是昨天更新的，奇怪的是用3.4.5本地dev是报这个错，build打包线上运行是可以的。看你用的是3.2.45版本，你换个版本试下看看。我将ViewUIPlus源码下载下来用vue各个版本本地运行都没事。

**Comment by GreenRun0912** [comment]
你package.json里版本前面是不是加了^，加了^这个的话只要你是3.x版本都会下载最新的3.4.5版本。你可以去掉前面的^就是下载指定版本。猜测你应该跟我一样是3.4.5版本报错，我刚试了3.2.45是没问题的。这个报错我刚在vue提了issue，可能是最新版本的vue更改了某些配置吧。
（1）^表示：匹配最近的一个大版本比如1.0.2 将会匹配到1.x.x，但不包括2.x.x
（2）~表示：匹配最近的小版本比如~1.0.2将会匹配1.0.x版本，但不匹配1.1.0

**Comment by GreenRun0912** [comment]
你package.json里版本前面是不是加了^，加了^这个的话只要你是3.x.x版本都会下载最新的3.4.5版本。你可以去掉前面的^就是下载指定版本。猜测你应该跟我一样是3.4.5版本报错，我刚试了3.2.45是没问题的。这个报错我刚在vue提了issue，可能是最新版本的vue更改了某些配置吧，ViewUIPlus可能需要兼容修改下。看到vue和ant-design-vue的社区里也有其他人提到了将vue升级到新版本报错的问题。
（1）^表示：匹配最近的一个大版本比如1.0.2 将会匹配到1.x.x，但不包括2.x.x
（2）~表示：匹配最近的小版本比如~1.0.2将会匹配1.0.x版本，但不匹配1.1.0

**Comment by chougaigai** [comment]
> 你package.json里版本前面是不是加了^，加了^这个的话只要你是3.x.x版本都会下载最新的3.4.5版本。你可以去掉前面的^就是下载指定版本。猜测你应该跟我一样是3.4.5版本报错，我刚试了3.2.45是没问题的。这个报错我刚在vue提了issue，可能是最新版本的vue更改了某些配置吧，ViewUIPlus可能需要兼容修改下。看到vue和ant-design-vue的社区里也有其他人提到了将vue升级到新版本报错的问题。 （1）^表示：匹配最近的一个大版本比如1.0.2 将会匹配到1.x.x，但不包括2.x.x （2）~表示：匹配最近的小版本比如~1.0.2将会匹配1.0.x版本，但不匹配1.1.0

谢谢大佬。可以了。
