### ISSUE TITLE
render 的写法模式下，为啥DatePicker onOk onChange的方法都走不进去？有大佬知道嘛？

### ISSUE THREAD

**Issue by yumeiqiang** [view-design/ViewUIPlus#348]
![image](https://github.com/view-design/ViewUIPlus/assets/16550302/1ce6ac48-fadc-449c-80a4-9e7c0ae4bb1a)

**Comment by s961121** [comment]
没解决吗 怎么回事

**Comment by zhengcsix** [comment]
试试 onOnChange  这种
