### ISSUE TITLE
[Bug Report]2.0版本的连文档都不提供了？

### ISSUE THREAD

**Issue by mcx1230** [view-design/ViewUIPlus#42]
### Environment
操作系统版本 / 浏览器版本 / Vue 版本等等信息

### Reproduction link
[https://www.iviewui.com/](https://www.iviewui.com/)

### Steps to reproduce
操作系统版本 / 浏览器版本 / Vue 版本等等信息

### What is expected?
操作系统版本 / 浏览器版本 / Vue 版本等等信息

### What is actually happening?
操作系统版本 / 浏览器版本 / Vue 版本等等信息

**Comment by youhunwl** [comment]
[http://v4.iviewui.com/](http://v4.iviewui.com/)
