### ISSUE TITLE
[Bug Report]Tree自定义节点内容 resolveComponent is not defined

### ISSUE THREAD

**Issue by Feellove** [view-design/ViewUIPlus#45]
### Environment
widow/Chrome版本 96.0.4664.45（正式版本） （64 位）/vue3

### Reproduction link
[https://run.iviewui.com/BYfe32sV](https://run.iviewui.com/BYfe32sV)

### Steps to reproduce
控制台

### What is expected?
正确显示

### What is actually happening?
页面报错，组件不显示

**Comment by icarusion** [comment]
到新版 Run 去试
