### ISSUE TITLE
想问一下大佬们，input的slot复合型输入框，用render来怎么写

### ISSUE THREAD

**Issue by fengliting** [view-design/ViewUIPlus#46]
（1）《Input》
        《template #append》
          《span》com《/span》
        《/template》
    《/Input》

（2）《Input》
        《span slot="append"》com《/span》
    《/Input》

上面（英文状态下展示有问题，换成中文的《》）（1）是iview的vue3官网的写法，（2）是iview的vue2的写法，vue2可以直接写标签，给个slot=“suffix”，就可以显示出来，现在要加上template的#prepend，这个要怎么render出来？希望有大佬能解答

**Comment by yumeiqiang** [comment]
请问下解决了嘛？render 中怎么写slot的

**Comment by fengliting** [comment]
> 请问下解决了嘛？render 中怎么写slot的

https://ask.csdn.net/questions/7721752?answer=53796039&spm=1001.2014.3001.5501

**Comment by ZMDreamer** [comment]
下面是我的代码，可以参考一下，在render里面dropdown
```
const renderFilterHeader = (_, key) => {
  const items = [
    { value: '1', title: '全选' },
    { value: '0', title: '反选' }
  ]
  return h(
    Dropdown,
    {
      class: 'filter-query',
      transfer: true,
      onOnClick: (e) => {
        checkChange(e, key)
      }
    },
    {
      default: () => h(Icon, {
        type: 'ios-funnel',
        title: '勾选'
      }),
      list: () => h(DropdownMenu, items.map((p) => {
        return h(
          DropdownItem,
          {
            name: p.value
          },
          p.title
        )
      })),
    })
}
````
