### ISSUE TITLE
[Bug Report]在Split控件下，按住分割线无法左右移动

### ISSUE THREAD

**Issue by baibaicloud** [view-design/ViewUIPlus#52]
### Environment
win11,谷歌浏览器，vue3

### Reproduction link
[https://run.iviewui.com/LcqAlfjJ](https://run.iviewui.com/LcqAlfjJ)

### Steps to reproduce
按住分割线拖动

### What is expected?
按住分割线能够左右拖动

### What is actually happening?
分割线固定住，无法左右拖动

**Comment by icarusion** [comment]
wrong link
