### ISSUE TITLE
[Bug Report]table render 组件 无法获取到props 内传递的参数

### ISSUE THREAD

**Issue by Gyxy** [view-design/ViewUIPlus#53]
### Environment
mscos 11.6.1 / chrome100 / vue3.0

### Reproduction link
[https://iviewui.com/view-ui-plus/component/form/table](https://iviewui.com/view-ui-plus/component/form/table)

### Steps to reproduce
1.进去官方文档
2.搜索table组件
3.查看自定义render相关代码
```
  h(resolveComponent('Button'), {
                                    props: {
                                        type: 'primary',
                                        size: 'small'
                                    },
                                    style: {
                                        marginRight: '5px'
                                    },
                                    onClick: () => {
                                        this.show(params.index)
                                    }
                                },
```

### What is expected?
table render Button props传递的 的type属性可以获取到 

### What is actually happening?
未获取到props传递的参数

**Comment by Gyxy** [comment]
props 内容直接放到外层对象中即可

**Comment by sunyangy** [comment]
我也有相同的问题，我不知道你说的 props 内容直接放到外层对象中即可 是什么意思，能告诉我具体做法吗，这是我的代码
return h(resolveComponent('Select'), {
              style: {
                // position: 'relative',
                // top: '0px'
              },
              props: {
                transfer: true,
                clearable: true,
                disabled: !params.row.isEdit || this.$route.query.isLook === 'true',
                value: params.row.exprOper || '=='
              },
              on: {
                'on-change': (event) => {
                  params.row.exprOper = event;
                  vm.student.data[params.index].exprOper = params.row.exprOper;
                  this.$emit('on-group', { eachObj: vm.student, index: this.index });
                }
              }
            }, 
             [this.exprOperList.map((item) => {
               return h(resolveComponent('Option'), { 
                  props: { value: item.value ,
                  } 
                }, item.label)
             })]
            );
