### ISSUE TITLE
[Bug Report]表单select组件，如果在多选的状态下，鼠标点击表单按钮，需要点两次才能触发校验

### ISSUE THREAD

**Issue by xingzejian** [view-design/ViewUIPlus#54]
### Environment
所有版本

### Reproduction link
[https://run.iviewui.com/p8IXJyAQ](https://run.iviewui.com/p8IXJyAQ)

### Steps to reproduce
1.将select设置为多选
2.选择一个值之后，不要点击其他位置，使下拉列表保持展开的状态
3.点击表单submit按钮

### What is expected?
当下拉列表展开的时候，第一次点击submit按钮应该触发表单校验

### What is actually happening?
当下拉列表展开的时候，第一次点击submit按钮没有触发表单校验，需要等待下拉列表折叠后，也就是第二次点击才能触发表单校验

**Comment by icarusion** [comment]
capture

**Comment by wudadaworker** [comment]
解决了吗，我也遇到了
