### ISSUE TITLE
[Bug Report]vite，vue main.js，import 'view-ui-plus/src/styles/index.less' ，提示 fonts/ionicons.ttf?v=3.0.0 not found

### ISSUE THREAD

**Issue by xinlei3166** [view-design/ViewUIPlus#57]
### Environment
mac / chrome 101.0.4951.64 / vue 3.2.20

### Reproduction link
[https://run.iviewui.com/WIeCe4dp](https://run.iviewui.com/WIeCe4dp)

### Steps to reproduce
使用vite   vue ，main.js 中 import 'view-ui-plus/src/styles/index.less' ，控制台提示 fonts/ionicons.ttf?v=3.0.0 not found，并且页面中icon看不见。

### What is expected?
定制主题后，icon正常显示。

### What is actually happening?
定制主题后，icon不显示。

**Comment by xuchangjunjx** [comment]
less变量导致的，在字体那个var里有设置字体文件的相对路径变量，vite下会有这样的问题，可以不用那个变量，直接在ionicons-font.less里改成./fonts，不实用变量就好里

**Comment by xinlei3166** [comment]
> less变量导致的，在字体那个var里有设置字体文件的相对路径变量，vite下会有这样的问题，可以不用那个变量，直接在ionicons-font.less里改成./fonts，不实用变量就好里

可以用，是个临时解决方案，多谢。

**Comment by hcp000** [comment]
我也碰到这个问题。我现在解决方案是吧 fonts的文件夹拷贝出来，放到public下。dev模式下没问题。然后在做build的时候fonts文件夹还是找不到。因为vite默认打包到assset下面，不知道有什么好的方式么？

**Comment by likuner** [comment]
可以参考我们的官方vite模版工程， 对您提到的问题做了处理：[view-ui-project-vite](https://github.com/view-design/view-ui-project-vite)

**Comment by joe105598055** [comment]
> 可以参考我们的官方vite模版工程， 对您提到的问题做了处理：[view-ui-project-vite](https://github.com/view-design/view-ui-project-vite)

在variable.less 定義的變量，並不能覆蓋覆蓋主題

**Comment by xuchangjunjx** [comment]
你好，如果你看到我这封邮件，说明我已收到你的信息。若有问题我会抽空回复你。

**Comment by zhengchangshun** [comment]
> 我也碰到这个问题。我现在解决方案是吧 fonts的文件夹拷贝出来，放到public下。dev模式下没问题。然后在做build的时候fonts文件夹还是找不到。因为vite默认打包到assset下面，不知道有什么好的方式么？

可以增加一个 `npm script : mv:icon`，将 fonts 移动至 assets 目录下。执行 bulid 的时候，`vite build && yarn mv:icon`

**Comment by huaixunanzhong** [comment]
> 可以参考我们的官方vite模版工程， 对您提到的问题做了处理：[view-ui-project-vite](https://github.com/view-design/view-ui-project-vite)

是怎么解决的?

**Comment by xuchangjunjx** [comment]
你好，如果你看到我这封邮件，说明我已收到你的信息。若有问题我会抽空回复你。
