### ISSUE TITLE
[Bug Report]InputNumber 丢失箭头样式，不能点击切换数字

### ISSUE THREAD

**Issue by karapeng** [view-design/ViewUIPlus#59]
### Environment
win11   edge  vue3

### Reproduction link
[https://run.iviewui.com/uNt3f9MK](https://run.iviewui.com/uNt3f9MK)

### Steps to reproduce
官方的   View Design Run 运行  InputNumber 都有问题

### What is expected?
InputNumber 能正常使用

### What is actually happening?
InputNumber 不能正常使用，InputNumber 丢失箭头样式，不能点击切换数字

**Comment by hcp000** [comment]
我这里也有同样的问题， 麻烦问下如何解决的
