### ISSUE TITLE
[Bug Report]ColorPicker 开启transfer 后，确定按钮  点击无效

### ISSUE THREAD

**Issue by karapeng** [view-design/ViewUIPlus#64]
### Environment
win11/edge/vue3.0

### Reproduction link
[https://run.iviewui.com/JaNTdh1E](https://run.iviewui.com/JaNTdh1E)

### Steps to reproduce
<ColorPicker v-model="color1" :transfer="true"  />

### What is expected?
ColorPicker开启 transfer 点击确定后，颜色能正常修改

### What is actually happening?
ColorPicker开启 transfer 点击确定后，无任何反应

**Comment by icarusion** [comment]
@likuner
