### ISSUE TITLE
[Bug Report]<InputNumber>上下箭头不显示

### ISSUE THREAD

**Issue by xufei0718** [view-design/ViewUIPlus#89]
### Environment
win11/edge102/vue3.2

### Reproduction link
[https://github.com/view-design/view-ui-project-vuecli](https://github.com/view-design/view-ui-project-vuecli)

### Steps to reproduce
1、下载官方提供的项目源码（view-ui-project-vuecli）
2、在views/Home.vue中加入 <InputNumber :max="10" :min="1" ></InputNumber>
3、在本地运行后页面输入框中没有上下箭头图标，只显示一条竖向分割线

### What is expected?
 <InputNumber>正常显示数字及上下箭头图标，并且点击点击可以改变数字。

### What is actually happening?
鼠标经过后只显示一条竖向分割线没有上下箭头，并且点击后数字无法改变。

**Comment by icarusion** [comment]
更新组新版
