### ISSUE TITLE
[Bug Report]Modal 的on-ok方法设置了visible=false，导致点确认按钮都会关闭Modal

### ISSUE THREAD

**Issue by Dahyzeng** [view-design/ViewUIPlus#91]
### Environment
vue ^2.6.10, "view-design": "^4.2.0",

### Reproduction link
[http://iviewui.com/view-ui-plus/component/view/modal](http://iviewui.com/view-ui-plus/component/view/modal)

### Steps to reproduce
在modal内部，使用了表单，点确认的时候会去验证表单，如果表单报错，此时不想关闭modal。但由于view-design 的modal组键on-ok源码：
if (this.loading) {
      this.buttonLoading = true;
   } else {
         this.visible = false;
         this.$emit('input', false);
 }
this.$emit('on-ok');
代码中this.visible = false;自动关闭了modal。虽然loading控制可以控制，但并不完美。需要使用者做这样的代码：
 this.loading = false;
 setTimeout(() => {
     this.loading = true;
 }, 100)；这样modal才不会关闭，并且有loading状态。

### What is expected?
期望能在on-ok方法中去掉this.visible = false，由使用者自己控制onOk事件modal的显隐控制。

### What is actually happening?
虽然loading控制可以控制，但并不完美。

**Comment by Dahyzeng** [comment]
<img width="950" alt="image" src="https://user-images.githubusercontent.com/8120004/173797047-c73a5711-bb91-4454-b8d9-b48511742ac2.png">

**Comment by icarusion** [comment]
使用问题

**Comment by 83920322** [comment]
同求解决方案

**Comment by Hitotsubashi** [comment]
草，这是我见过最脑残的设定了。麻烦作者可否学一下element-ui的设定。on-ok会自动关掉modal，然后loading设置为false不能关闭loading动画
