### ISSUE TITLE
[Bug Report]导给设置了icon的Input，添加clearable，会导致输入以后icon消失

### ISSUE THREAD

**Issue by Younglina** [view-design/ViewUIPlus#95]
### Environment
vue ^2.6.10, "view-design": "^4.2.0",

### Reproduction link
[https://run.iviewui.com/PChDwDQh](https://run.iviewui.com/PChDwDQh)

### Steps to reproduce
导给设置了icon的Input，添加clearable，输入内容以后icon消失

### What is expected?
hover时显示close，其他时候显示原icon

### What is actually happening?
hover时显示close，其他时候原icon消失

**Comment by icarusion** [comment]
clearable 优先级高于 icon

**Comment by Younglina** [comment]
> clearable 优先级高于 icon

可是hover完以后，之前的icon就不会显示了
